# The following is automatically generated by code_factory.py

from numba import njit


@njit
def scores(index, cell_tally, data):
    offset = cell_tally["scores_offset"]
    return data[offset + index]


@njit
def scores_all(cell_tally, data):
    start = cell_tally["scores_offset"]
    size = cell_tally["scores_length"]
    end = start + size
    return data[start:end]


@njit
def scores_last(cell_tally, data):
    start = cell_tally["scores_offset"]
    size = cell_tally["scores_length"]
    end = start + size
    return data[end - 1]


@njit
def scores_chunk(start, length, cell_tally, data):
    start += cell_tally["scores_offset"]
    end = start + length
    return data[start:end]


@njit
def mu(index, cell_tally, data):
    offset = cell_tally["mu_offset"]
    return data[offset + index]


@njit
def mu_all(cell_tally, data):
    start = cell_tally["mu_offset"]
    size = cell_tally["mu_length"]
    end = start + size
    return data[start:end]


@njit
def mu_last(cell_tally, data):
    start = cell_tally["mu_offset"]
    size = cell_tally["mu_length"]
    end = start + size
    return data[end - 1]


@njit
def mu_chunk(start, length, cell_tally, data):
    start += cell_tally["mu_offset"]
    end = start + length
    return data[start:end]


@njit
def azi(index, cell_tally, data):
    offset = cell_tally["azi_offset"]
    return data[offset + index]


@njit
def azi_all(cell_tally, data):
    start = cell_tally["azi_offset"]
    size = cell_tally["azi_length"]
    end = start + size
    return data[start:end]


@njit
def azi_last(cell_tally, data):
    start = cell_tally["azi_offset"]
    size = cell_tally["azi_length"]
    end = start + size
    return data[end - 1]


@njit
def azi_chunk(start, length, cell_tally, data):
    start += cell_tally["azi_offset"]
    end = start + length
    return data[start:end]


@njit
def energy(index, cell_tally, data):
    offset = cell_tally["energy_offset"]
    return data[offset + index]


@njit
def energy_all(cell_tally, data):
    start = cell_tally["energy_offset"]
    size = cell_tally["energy_length"]
    end = start + size
    return data[start:end]


@njit
def energy_last(cell_tally, data):
    start = cell_tally["energy_offset"]
    size = cell_tally["energy_length"]
    end = start + size
    return data[end - 1]


@njit
def energy_chunk(start, length, cell_tally, data):
    start += cell_tally["energy_offset"]
    end = start + length
    return data[start:end]


@njit
def time(index, cell_tally, data):
    offset = cell_tally["time_offset"]
    return data[offset + index]


@njit
def time_all(cell_tally, data):
    start = cell_tally["time_offset"]
    size = cell_tally["time_length"]
    end = start + size
    return data[start:end]


@njit
def time_last(cell_tally, data):
    start = cell_tally["time_offset"]
    size = cell_tally["time_length"]
    end = start + size
    return data[end - 1]


@njit
def time_chunk(start, length, cell_tally, data):
    start += cell_tally["time_offset"]
    end = start + length
    return data[start:end]


@njit
def bin(index, cell_tally, data):
    offset = cell_tally["bin_offset"]
    return data[offset + index]


@njit
def bin_all(cell_tally, data):
    start = cell_tally["bin_offset"]
    size = cell_tally["bin_length"]
    end = start + size
    return data[start:end]


@njit
def bin_last(cell_tally, data):
    start = cell_tally["bin_offset"]
    size = cell_tally["bin_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_chunk(start, length, cell_tally, data):
    start += cell_tally["bin_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_sum(index, cell_tally, data):
    offset = cell_tally["bin_sum_offset"]
    return data[offset + index]


@njit
def bin_sum_all(cell_tally, data):
    start = cell_tally["bin_sum_offset"]
    size = cell_tally["bin_sum_length"]
    end = start + size
    return data[start:end]


@njit
def bin_sum_last(cell_tally, data):
    start = cell_tally["bin_sum_offset"]
    size = cell_tally["bin_sum_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_sum_chunk(start, length, cell_tally, data):
    start += cell_tally["bin_sum_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_sum_square(index, cell_tally, data):
    offset = cell_tally["bin_sum_square_offset"]
    return data[offset + index]


@njit
def bin_sum_square_all(cell_tally, data):
    start = cell_tally["bin_sum_square_offset"]
    size = cell_tally["bin_sum_square_length"]
    end = start + size
    return data[start:end]


@njit
def bin_sum_square_last(cell_tally, data):
    start = cell_tally["bin_sum_square_offset"]
    size = cell_tally["bin_sum_square_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_sum_square_chunk(start, length, cell_tally, data):
    start += cell_tally["bin_sum_square_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_shape(index, cell_tally, data):
    offset = cell_tally["bin_shape_offset"]
    return data[offset + index]


@njit
def bin_shape_all(cell_tally, data):
    start = cell_tally["bin_shape_offset"]
    size = cell_tally["bin_shape_length"]
    end = start + size
    return data[start:end]


@njit
def bin_shape_last(cell_tally, data):
    start = cell_tally["bin_shape_offset"]
    size = cell_tally["bin_shape_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_shape_chunk(start, length, cell_tally, data):
    start += cell_tally["bin_shape_offset"]
    end = start + length
    return data[start:end]
