# The following is automatically generated by code_factory.py

from numba import njit


@njit
def universe_IDs(index, lattice, data):
    offset = lattice["universe_IDs_offset"]
    return data[offset + index]


@njit
def universe_IDs_all(lattice, data):
    start = lattice["universe_IDs_offset"]
    size = lattice["N_universe"]
    end = start + size
    return data[start:end]


@njit
def universe_IDs_last(lattice, data):
    start = lattice["universe_IDs_offset"]
    size = lattice["N_universe"]
    end = start + size
    return data[end - 1]


@njit
def universe_IDs_chunk(start, length, lattice, data):
    start += lattice["universe_IDs_offset"]
    end = start + length
    return data[start:end]
