# The following is automatically generated by code_factory.py

from numba import njit


@njit
def scores(index, mesh_tally, data):
    offset = mesh_tally["scores_offset"]
    return data[offset + index]


@njit
def scores_all(mesh_tally, data):
    start = mesh_tally["scores_offset"]
    size = mesh_tally["scores_length"]
    end = start + size
    return data[start:end]


@njit
def scores_last(mesh_tally, data):
    start = mesh_tally["scores_offset"]
    size = mesh_tally["scores_length"]
    end = start + size
    return data[end - 1]


@njit
def scores_chunk(start, length, mesh_tally, data):
    start += mesh_tally["scores_offset"]
    end = start + length
    return data[start:end]


@njit
def mu(index, mesh_tally, data):
    offset = mesh_tally["mu_offset"]
    return data[offset + index]


@njit
def mu_all(mesh_tally, data):
    start = mesh_tally["mu_offset"]
    size = mesh_tally["mu_length"]
    end = start + size
    return data[start:end]


@njit
def mu_last(mesh_tally, data):
    start = mesh_tally["mu_offset"]
    size = mesh_tally["mu_length"]
    end = start + size
    return data[end - 1]


@njit
def mu_chunk(start, length, mesh_tally, data):
    start += mesh_tally["mu_offset"]
    end = start + length
    return data[start:end]


@njit
def azi(index, mesh_tally, data):
    offset = mesh_tally["azi_offset"]
    return data[offset + index]


@njit
def azi_all(mesh_tally, data):
    start = mesh_tally["azi_offset"]
    size = mesh_tally["azi_length"]
    end = start + size
    return data[start:end]


@njit
def azi_last(mesh_tally, data):
    start = mesh_tally["azi_offset"]
    size = mesh_tally["azi_length"]
    end = start + size
    return data[end - 1]


@njit
def azi_chunk(start, length, mesh_tally, data):
    start += mesh_tally["azi_offset"]
    end = start + length
    return data[start:end]


@njit
def energy(index, mesh_tally, data):
    offset = mesh_tally["energy_offset"]
    return data[offset + index]


@njit
def energy_all(mesh_tally, data):
    start = mesh_tally["energy_offset"]
    size = mesh_tally["energy_length"]
    end = start + size
    return data[start:end]


@njit
def energy_last(mesh_tally, data):
    start = mesh_tally["energy_offset"]
    size = mesh_tally["energy_length"]
    end = start + size
    return data[end - 1]


@njit
def energy_chunk(start, length, mesh_tally, data):
    start += mesh_tally["energy_offset"]
    end = start + length
    return data[start:end]


@njit
def time(index, mesh_tally, data):
    offset = mesh_tally["time_offset"]
    return data[offset + index]


@njit
def time_all(mesh_tally, data):
    start = mesh_tally["time_offset"]
    size = mesh_tally["time_length"]
    end = start + size
    return data[start:end]


@njit
def time_last(mesh_tally, data):
    start = mesh_tally["time_offset"]
    size = mesh_tally["time_length"]
    end = start + size
    return data[end - 1]


@njit
def time_chunk(start, length, mesh_tally, data):
    start += mesh_tally["time_offset"]
    end = start + length
    return data[start:end]


@njit
def bin(index, mesh_tally, data):
    offset = mesh_tally["bin_offset"]
    return data[offset + index]


@njit
def bin_all(mesh_tally, data):
    start = mesh_tally["bin_offset"]
    size = mesh_tally["bin_length"]
    end = start + size
    return data[start:end]


@njit
def bin_last(mesh_tally, data):
    start = mesh_tally["bin_offset"]
    size = mesh_tally["bin_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_chunk(start, length, mesh_tally, data):
    start += mesh_tally["bin_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_sum(index, mesh_tally, data):
    offset = mesh_tally["bin_sum_offset"]
    return data[offset + index]


@njit
def bin_sum_all(mesh_tally, data):
    start = mesh_tally["bin_sum_offset"]
    size = mesh_tally["bin_sum_length"]
    end = start + size
    return data[start:end]


@njit
def bin_sum_last(mesh_tally, data):
    start = mesh_tally["bin_sum_offset"]
    size = mesh_tally["bin_sum_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_sum_chunk(start, length, mesh_tally, data):
    start += mesh_tally["bin_sum_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_sum_square(index, mesh_tally, data):
    offset = mesh_tally["bin_sum_square_offset"]
    return data[offset + index]


@njit
def bin_sum_square_all(mesh_tally, data):
    start = mesh_tally["bin_sum_square_offset"]
    size = mesh_tally["bin_sum_square_length"]
    end = start + size
    return data[start:end]


@njit
def bin_sum_square_last(mesh_tally, data):
    start = mesh_tally["bin_sum_square_offset"]
    size = mesh_tally["bin_sum_square_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_sum_square_chunk(start, length, mesh_tally, data):
    start += mesh_tally["bin_sum_square_offset"]
    end = start + length
    return data[start:end]


@njit
def bin_shape(index, mesh_tally, data):
    offset = mesh_tally["bin_shape_offset"]
    return data[offset + index]


@njit
def bin_shape_all(mesh_tally, data):
    start = mesh_tally["bin_shape_offset"]
    size = mesh_tally["bin_shape_length"]
    end = start + size
    return data[start:end]


@njit
def bin_shape_last(mesh_tally, data):
    start = mesh_tally["bin_shape_offset"]
    size = mesh_tally["bin_shape_length"]
    end = start + size
    return data[end - 1]


@njit
def bin_shape_chunk(start, length, mesh_tally, data):
    start += mesh_tally["bin_shape_offset"]
    end = start + length
    return data[start:end]
