# The following is automatically generated by code_factory.py

from numba import njit


@njit
def spectrum_probability_grid(index, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    return data[offset + index]


@njit
def spectrum_probability_grid_all(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    return data[start:end]


@njit
def spectrum_probability_grid_last(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    return data[end - 1]


@njit
def spectrum_probability_grid_chunk(start, length, neutron_inelastic_scattering_reaction, data):
    start += neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def spectrum_probability(index, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    return data[offset + index]


@njit
def spectrum_probability_all(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_length"]
    end = start + size
    return data[start:end]


@njit
def spectrum_probability_last(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_length"]
    end = start + size
    return data[end - 1]


@njit
def spectrum_probability_chunk(start, length, neutron_inelastic_scattering_reaction, data):
    start += neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    end = start + length
    return data[start:end]


@njit
def energy_spectrum_IDs(index, neutron_inelastic_scattering_reaction, data):
    offset = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    return data[offset + index]


@njit
def energy_spectrum_IDs_all(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = neutron_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    return data[start:end]


@njit
def energy_spectrum_IDs_last(neutron_inelastic_scattering_reaction, data):
    start = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = neutron_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    return data[end - 1]


@njit
def energy_spectrum_IDs_chunk(start, length, neutron_inelastic_scattering_reaction, data):
    start += neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    end = start + length
    return data[start:end]
