# The following is automatically generated by code_factory.py

from numba import njit


@njit
def value(index, pdf_distribution, data):
    offset = pdf_distribution["value_offset"]
    return data[offset + index]


@njit
def value_all(pdf_distribution, data):
    start = pdf_distribution["value_offset"]
    size = pdf_distribution["value_length"]
    end = start + size
    return data[start:end]


@njit
def value_last(pdf_distribution, data):
    start = pdf_distribution["value_offset"]
    size = pdf_distribution["value_length"]
    end = start + size
    return data[end - 1]


@njit
def value_chunk(start, length, pdf_distribution, data):
    start += pdf_distribution["value_offset"]
    end = start + length
    return data[start:end]


@njit
def pdf(index, pdf_distribution, data):
    offset = pdf_distribution["pdf_offset"]
    return data[offset + index]


@njit
def pdf_all(pdf_distribution, data):
    start = pdf_distribution["pdf_offset"]
    size = pdf_distribution["pdf_length"]
    end = start + size
    return data[start:end]


@njit
def pdf_last(pdf_distribution, data):
    start = pdf_distribution["pdf_offset"]
    size = pdf_distribution["pdf_length"]
    end = start + size
    return data[end - 1]


@njit
def pdf_chunk(start, length, pdf_distribution, data):
    start += pdf_distribution["pdf_offset"]
    end = start + length
    return data[start:end]


@njit
def cdf(index, pdf_distribution, data):
    offset = pdf_distribution["cdf_offset"]
    return data[offset + index]


@njit
def cdf_all(pdf_distribution, data):
    start = pdf_distribution["cdf_offset"]
    size = pdf_distribution["cdf_length"]
    end = start + size
    return data[start:end]


@njit
def cdf_last(pdf_distribution, data):
    start = pdf_distribution["cdf_offset"]
    size = pdf_distribution["cdf_length"]
    end = start + size
    return data[end - 1]


@njit
def cdf_chunk(start, length, pdf_distribution, data):
    start += pdf_distribution["cdf_offset"]
    end = start + length
    return data[start:end]
