# The following is automatically generated by code_factory.py

from mcdc.code_factory.code_factory import into_dtype

particle_data = into_dtype([
    ('x', 'f8'),
    ('y', 'f8'),
    ('z', 'f8'),
    ('t', 'f8'),
    ('ux', 'f8'),
    ('uy', 'f8'),
    ('uz', 'f8'),
    ('g', 'i8'),
    ('E', 'f8'),
    ('w', 'f8'),
    ('particle_type', 'i8'),
    ('rng_seed', 'u8'),
])

particle = into_dtype([
    ('cell_ID', 'i8'),
    ('material_ID', 'i8'),
    ('surface_ID', 'i8'),
    ('alive', '?'),
    ('fresh', '?'),
    ('event', 'i8'),
    ('x', 'f8'),
    ('y', 'f8'),
    ('z', 'f8'),
    ('t', 'f8'),
    ('ux', 'f8'),
    ('uy', 'f8'),
    ('uz', 'f8'),
    ('g', 'i8'),
    ('E', 'f8'),
    ('w', 'f8'),
    ('particle_type', 'i8'),
    ('rng_seed', 'u8'),
])

cell = into_dtype([
    ('name', 'U32'),
    ('fill_translated', '?'),
    ('fill_rotated', '?'),
    ('translation', 'f8', (3,)),
    ('rotation', 'f8', (3,)),
    ('region_RPN_tokens_offset', 'i8'),
    ('region_RPN_tokens_length', 'i8'),
    ('N_surface', 'i8'),
    ('surface_IDs_offset', 'i8'),
    ('N_tally', 'i8'),
    ('tally_IDs_offset', 'i8'),
    ('fill_type', 'i8'),
    ('fill_ID', 'i8'),
    ('ID', 'i8'),
])

lattice = into_dtype([
    ('name', 'U32'),
    ('x0', 'f8'),
    ('dx', 'f8'),
    ('Nx', 'i8'),
    ('y0', 'f8'),
    ('dy', 'f8'),
    ('Ny', 'i8'),
    ('z0', 'f8'),
    ('dz', 'f8'),
    ('Nz', 'i8'),
    ('universe_IDs_offset', 'i8'),
    ('universe_IDs_length', 'i8'),
    ('ID', 'i8'),
])

material = into_dtype([
    ('name', 'U32'),
    ('fissionable', '?'),
    ('ID', 'i8'),
    ('child_type', 'i8'),
    ('child_ID', 'i8'),
])

cell_tally = into_dtype([
    ('cell_ID', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

universe = into_dtype([
    ('name', 'U32'),
    ('N_cell', 'i8'),
    ('cell_IDs_offset', 'i8'),
    ('ID', 'i8'),
])

data = into_dtype([
    ('ID', 'i8'),
    ('child_type', 'i8'),
    ('child_ID', 'i8'),
])

none_data = into_dtype([
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

polynomial_data = into_dtype([
    ('coefficients_offset', 'i8'),
    ('coefficients_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

table_data = into_dtype([
    ('x_offset', 'i8'),
    ('x_length', 'i8'),
    ('y_offset', 'i8'),
    ('y_length', 'i8'),
    ('interpolation', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

distribution = into_dtype([
    ('ID', 'i8'),
    ('child_type', 'i8'),
    ('child_ID', 'i8'),
])

evaporation_distribution = into_dtype([
    ('nuclear_temperature_ID', 'i8'),
    ('restriction_energy', 'f8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

kalbach_mann_distribution = into_dtype([
    ('energy_offset', 'i8'),
    ('energy_length', 'i8'),
    ('offset_offset', 'i8'),
    ('offset_length', 'i8'),
    ('energy_out_offset', 'i8'),
    ('energy_out_length', 'i8'),
    ('pdf_offset', 'i8'),
    ('pdf_length', 'i8'),
    ('cdf_offset', 'i8'),
    ('cdf_length', 'i8'),
    ('precompound_factor_offset', 'i8'),
    ('precompound_factor_length', 'i8'),
    ('angular_slope_offset', 'i8'),
    ('angular_slope_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

level_scattering_distribution = into_dtype([
    ('C1', 'f8'),
    ('C2', 'f8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

maxwellian_distribution = into_dtype([
    ('nuclear_temperature_ID', 'i8'),
    ('restriction_energy', 'f8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

multi_table_distribution = into_dtype([
    ('grid_offset', 'i8'),
    ('grid_length', 'i8'),
    ('offset_offset', 'i8'),
    ('offset_length', 'i8'),
    ('value_offset', 'i8'),
    ('value_length', 'i8'),
    ('pdf_offset', 'i8'),
    ('pdf_length', 'i8'),
    ('cdf_offset', 'i8'),
    ('cdf_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

nbody_distribution = into_dtype([
    ('value_offset', 'i8'),
    ('value_length', 'i8'),
    ('pdf_offset', 'i8'),
    ('pdf_length', 'i8'),
    ('cdf_offset', 'i8'),
    ('cdf_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

none_distribution = into_dtype([
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

pmf_distribution = into_dtype([
    ('value_offset', 'i8'),
    ('value_length', 'i8'),
    ('pmf_offset', 'i8'),
    ('pmf_length', 'i8'),
    ('cmf_offset', 'i8'),
    ('cmf_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

tabulated_distribution = into_dtype([
    ('value_offset', 'i8'),
    ('value_length', 'i8'),
    ('pdf_offset', 'i8'),
    ('pdf_length', 'i8'),
    ('cdf_offset', 'i8'),
    ('cdf_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

tabulated_energy_angle_distribution = into_dtype([
    ('energy_offset', 'i8'),
    ('energy_length', 'i8'),
    ('offset_offset', 'i8'),
    ('offset_length', 'i8'),
    ('energy_out_offset', 'i8'),
    ('energy_out_length', 'i8'),
    ('pdf_offset', 'i8'),
    ('pdf_length', 'i8'),
    ('cdf_offset', 'i8'),
    ('cdf_length', 'i8'),
    ('cosine_offset__offset', 'i8'),
    ('cosine_offset__length', 'i8'),
    ('cosine_offset', 'i8'),
    ('cosine_length', 'i8'),
    ('cosine_pdf_offset', 'i8'),
    ('cosine_pdf_length', 'i8'),
    ('cosine_cdf_offset', 'i8'),
    ('cosine_cdf_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

gpu_meta = into_dtype([
    ('state_pointer', 'u8'),
    ('source_program_pointer', 'u8'),
    ('precursor_program_pointer', 'u8'),
    ('structure_pointer', 'u8'),
    ('data_pointer', 'u8'),
])

native_material = into_dtype([
    ('N_nuclide', 'i8'),
    ('nuclide_IDs_offset', 'i8'),
    ('nuclide_densities_offset', 'i8'),
    ('nuclide_densities_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

multigroup_material = into_dtype([
    ('G', 'i8'),
    ('J', 'i8'),
    ('mgxs_speed_offset', 'i8'),
    ('mgxs_speed_length', 'i8'),
    ('mgxs_decay_rate_offset', 'i8'),
    ('mgxs_decay_rate_length', 'i8'),
    ('mgxs_capture_offset', 'i8'),
    ('mgxs_capture_length', 'i8'),
    ('mgxs_scatter_offset', 'i8'),
    ('mgxs_scatter_length', 'i8'),
    ('mgxs_fission_offset', 'i8'),
    ('mgxs_fission_length', 'i8'),
    ('mgxs_total_offset', 'i8'),
    ('mgxs_total_length', 'i8'),
    ('mgxs_nu_s_offset', 'i8'),
    ('mgxs_nu_s_length', 'i8'),
    ('mgxs_nu_p_offset', 'i8'),
    ('mgxs_nu_p_length', 'i8'),
    ('mgxs_nu_d_offset', 'i8'),
    ('mgxs_nu_d_length', 'i8'),
    ('mgxs_nu_d_total_offset', 'i8'),
    ('mgxs_nu_d_total_length', 'i8'),
    ('mgxs_nu_f_offset', 'i8'),
    ('mgxs_nu_f_length', 'i8'),
    ('mgxs_chi_s_offset', 'i8'),
    ('mgxs_chi_s_length', 'i8'),
    ('mgxs_chi_p_offset', 'i8'),
    ('mgxs_chi_p_length', 'i8'),
    ('mgxs_chi_d_offset', 'i8'),
    ('mgxs_chi_d_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

nuclide = into_dtype([
    ('name', 'U32'),
    ('temperature', 'f8'),
    ('atomic_weight_ratio', 'f8'),
    ('fissionable', '?'),
    ('excitation_level', 'i8'),
    ('xs_energy_grid_offset', 'i8'),
    ('xs_energy_grid_length', 'i8'),
    ('total_xs_offset', 'i8'),
    ('total_xs_length', 'i8'),
    ('elastic_xs_offset', 'i8'),
    ('elastic_xs_length', 'i8'),
    ('capture_xs_offset', 'i8'),
    ('capture_xs_length', 'i8'),
    ('inelastic_xs_offset', 'i8'),
    ('inelastic_xs_length', 'i8'),
    ('fission_xs_offset', 'i8'),
    ('fission_xs_length', 'i8'),
    ('N_elastic_scattering_reaction', 'i8'),
    ('elastic_scattering_reaction_IDs_offset', 'i8'),
    ('N_capture_reaction', 'i8'),
    ('capture_reaction_IDs_offset', 'i8'),
    ('N_inelastic_scattering_reaction', 'i8'),
    ('inelastic_scattering_reaction_IDs_offset', 'i8'),
    ('N_fission_reaction', 'i8'),
    ('fission_reaction_IDs_offset', 'i8'),
    ('fission_prompt_multiplicity_ID', 'i8'),
    ('fission_delayed_multiplicity_ID', 'i8'),
    ('N_fission_delayed_precursor', 'i8'),
    ('fission_delayed_fractions_offset', 'i8'),
    ('fission_delayed_fractions_length', 'i8'),
    ('fission_delayed_decay_rates_offset', 'i8'),
    ('fission_delayed_decay_rates_length', 'i8'),
    ('N_fission_delayed_spectrum', 'i8'),
    ('fission_delayed_spectrum_IDs_offset', 'i8'),
    ('ID', 'i8'),
])

mesh = into_dtype([
    ('name', 'U32'),
    ('N_bin', 'i8'),
    ('Nx', 'i8'),
    ('Ny', 'i8'),
    ('Nz', 'i8'),
    ('ID', 'i8'),
    ('child_type', 'i8'),
    ('child_ID', 'i8'),
])

structured_mesh = into_dtype([
    ('x_offset', 'i8'),
    ('x_length', 'i8'),
    ('y_offset', 'i8'),
    ('y_length', 'i8'),
    ('z_offset', 'i8'),
    ('z_length', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

uniform_mesh = into_dtype([
    ('x0', 'f8'),
    ('dx', 'f8'),
    ('Nx', 'i8'),
    ('y0', 'f8'),
    ('dy', 'f8'),
    ('Ny', 'i8'),
    ('z0', 'f8'),
    ('dz', 'f8'),
    ('Nz', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

neutron_capture_reaction = into_dtype([
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

neutron_elastic_scattering_reaction = into_dtype([
    ('mu_table_ID', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

neutron_fission_reaction = into_dtype([
    ('angle_type', 'i8'),
    ('mu_ID', 'i8'),
    ('spectrum_ID', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

neutron_inelastic_scattering_reaction = into_dtype([
    ('multiplicity', 'i8'),
    ('angle_type', 'i8'),
    ('mu_ID', 'i8'),
    ('N_spectrum_probability_bin', 'i8'),
    ('N_spectrum', 'i8'),
    ('spectrum_probability_grid_offset', 'i8'),
    ('spectrum_probability_grid_length', 'i8'),
    ('spectrum_probability_offset', 'i8'),
    ('spectrum_probability_length', 'i8'),
    ('N_energy_spectrum', 'i8'),
    ('energy_spectrum_IDs_offset', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

particle_bank = into_dtype([
    ('size', 'i8', (1,)),
    ('tag', 'U32'),
])

reaction = into_dtype([
    ('MT', 'i8'),
    ('xs_offset', 'i8'),
    ('xs_length', 'i8'),
    ('xs_offset_', 'i8'),
    ('reference_frame', 'i8'),
    ('ID', 'i8'),
    ('child_type', 'i8'),
    ('child_ID', 'i8'),
])

settings = into_dtype([
    ('N_particle', 'i8'),
    ('N_batch', 'i8'),
    ('rng_seed', 'i8'),
    ('multigroup_mode', '?'),
    ('eigenvalue_mode', '?'),
    ('N_inactive', 'i8'),
    ('N_active', 'i8'),
    ('N_cycle', 'i8'),
    ('k_init', 'f8'),
    ('use_gyration_radius', '?'),
    ('gyration_radius_type', 'i8'),
    ('use_source_file', '?'),
    ('source_file_name', 'U32'),
    ('time_boundary', 'f8'),
    ('output_name', 'U32'),
    ('use_progress_bar', '?'),
    ('N_census', 'i8'),
    ('census_time_offset', 'i8'),
    ('census_time_length', 'i8'),
    ('use_census_based_tally', '?'),
    ('census_tally_frequency', 'i8'),
    ('save_particle', '?'),
    ('active_bank_buffer', 'i8'),
    ('census_bank_buffer_ratio', 'f8'),
    ('source_bank_buffer_ratio', 'f8'),
    ('future_bank_buffer_ratio', 'f8'),
    ('target_gpu', '?'),
])

implicit_capture = into_dtype([
    ('active', '?'),
])

population_control = into_dtype([
    ('active', '?'),
])

weight_roulette = into_dtype([
    ('weight_threshold', 'f8'),
    ('weight_target', 'f8'),
])

weighted_emission = into_dtype([
    ('active', '?'),
    ('weight_target', 'f8'),
])

source = into_dtype([
    ('name', 'U32'),
    ('point_source', '?'),
    ('point', 'f8', (3,)),
    ('x', 'f8', (2,)),
    ('y', 'f8', (2,)),
    ('z', 'f8', (2,)),
    ('isotropic_direction', '?'),
    ('mono_direction', '?'),
    ('white_direction', '?'),
    ('direction', 'f8', (3,)),
    ('mono_energetic', '?'),
    ('energy_group', 'i8'),
    ('energy', 'f8'),
    ('energy_group_pmf_ID', 'i8'),
    ('energy_pdf_ID', 'i8'),
    ('discrete_time', '?'),
    ('time', 'f8'),
    ('time_range', 'f8', (2,)),
    ('particle_type', 'i8'),
    ('probability', 'f8'),
    ('ID', 'i8'),
])

surface = into_dtype([
    ('type', 'i8'),
    ('name', 'U32'),
    ('boundary_condition', 'i8'),
    ('A', 'f8'),
    ('B', 'f8'),
    ('C', 'f8'),
    ('D', 'f8'),
    ('E', 'f8'),
    ('F', 'f8'),
    ('G', 'f8'),
    ('H', 'f8'),
    ('I', 'f8'),
    ('J', 'f8'),
    ('linear', '?'),
    ('nx', 'f8'),
    ('ny', 'f8'),
    ('nz', 'f8'),
    ('moving', '?'),
    ('N_move', 'i8'),
    ('N_move_grid', 'i8'),
    ('move_velocities_offset', 'i8'),
    ('move_velocities_length', 'i8'),
    ('move_durations_offset', 'i8'),
    ('move_durations_length', 'i8'),
    ('move_time_grid_offset', 'i8'),
    ('move_time_grid_length', 'i8'),
    ('move_translations_offset', 'i8'),
    ('move_translations_length', 'i8'),
    ('N_tally', 'i8'),
    ('tally_IDs_offset', 'i8'),
    ('ID', 'i8'),
])

surface_tally = into_dtype([
    ('surface_ID', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

tally = into_dtype([
    ('name', 'U32'),
    ('scores_offset', 'i8'),
    ('scores_length', 'i8'),
    ('multipliers_offset', 'i8'),
    ('multipliers_length', 'i8'),
    ('mu_offset', 'i8'),
    ('mu_length', 'i8'),
    ('azi_offset', 'i8'),
    ('azi_length', 'i8'),
    ('polar_reference', 'f8', (3,)),
    ('energy_offset', 'i8'),
    ('energy_length', 'i8'),
    ('time_offset', 'i8'),
    ('time_length', 'i8'),
    ('filter_direction', '?'),
    ('filter_energy', '?'),
    ('filter_time', '?'),
    ('bin_offset', 'i8'),
    ('bin_length', 'i8'),
    ('bin_sum_offset', 'i8'),
    ('bin_sum_length', 'i8'),
    ('bin_sum_square_offset', 'i8'),
    ('bin_sum_square_length', 'i8'),
    ('bin_shape_offset', 'i8'),
    ('bin_shape_length', 'i8'),
    ('stride_mu', 'i8'),
    ('stride_azi', 'i8'),
    ('stride_energy', 'i8'),
    ('stride_time', 'i8'),
    ('ID', 'i8'),
    ('child_type', 'i8'),
    ('child_ID', 'i8'),
])

global_tally = into_dtype([
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

mesh_tally = into_dtype([
    ('mesh_ID', 'i8'),
    ('stride_z', 'i8'),
    ('stride_y', 'i8'),
    ('stride_x', 'i8'),
    ('ID', 'i8'),
    ('parent_ID', 'i8'),
])

bank_active = into_dtype([
    ('size', 'i8', (1,)),
    ('tag', 'U32'),
    ('particles', particle, (100,)),
])

bank_census = into_dtype([
    ('size', 'i8', (1,)),
    ('tag', 'U32'),
    ('particles', particle, (0,)),
])

bank_source = into_dtype([
    ('size', 'i8', (1,)),
    ('tag', 'U32'),
    ('particles', particle, (0,)),
])

bank_future = into_dtype([
    ('size', 'i8', (1,)),
    ('tag', 'U32'),
    ('particles', particle, (0,)),
])

simulation = into_dtype([
    ('data', data, (1,)),
    ('N_data', 'i8'),
    ('none_data', none_data, (1,)),
    ('N_none_data', 'i8'),
    ('polynomial_data', polynomial_data, (0,)),
    ('N_polynomial_data', 'i8'),
    ('table_data', table_data, (0,)),
    ('N_table_data', 'i8'),
    ('distributions', distribution, (3,)),
    ('N_distribution', 'i8'),
    ('evaporation_distributions', evaporation_distribution, (0,)),
    ('N_evaporation_distribution', 'i8'),
    ('kalbach_mann_distributions', kalbach_mann_distribution, (0,)),
    ('N_kalbach_mann_distribution', 'i8'),
    ('level_scattering_distributions', level_scattering_distribution, (0,)),
    ('N_level_scattering_distribution', 'i8'),
    ('maxwellian_distributions', maxwellian_distribution, (0,)),
    ('N_maxwellian_distribution', 'i8'),
    ('multi_table_distributions', multi_table_distribution, (0,)),
    ('N_multi_table_distribution', 'i8'),
    ('nbody_distributions', nbody_distribution, (0,)),
    ('N_nbody_distribution', 'i8'),
    ('none_distributions', none_distribution, (1,)),
    ('N_none_distribution', 'i8'),
    ('pmf_distributions', pmf_distribution, (1,)),
    ('N_pmf_distribution', 'i8'),
    ('tabulated_distributions', tabulated_distribution, (1,)),
    ('N_tabulated_distribution', 'i8'),
    ('tabulated_energy_angle_distributions', tabulated_energy_angle_distribution, (0,)),
    ('N_tabulated_energy_angle_distribution', 'i8'),
    ('materials', material, (1,)),
    ('N_material', 'i8'),
    ('native_materials', native_material, (0,)),
    ('N_native_material', 'i8'),
    ('multigroup_materials', multigroup_material, (1,)),
    ('N_multigroup_material', 'i8'),
    ('nuclides', nuclide, (0,)),
    ('N_nuclide', 'i8'),
    ('neutron_capture_reactions', neutron_capture_reaction, (0,)),
    ('N_neutron_capture_reaction', 'i8'),
    ('neutron_elastic_scattering_reactions', neutron_elastic_scattering_reaction, (0,)),
    ('N_neutron_elastic_scattering_reaction', 'i8'),
    ('neutron_fission_reactions', neutron_fission_reaction, (0,)),
    ('N_neutron_fission_reaction', 'i8'),
    ('neutron_inelastic_scattering_reactions', neutron_inelastic_scattering_reaction, (0,)),
    ('N_neutron_inelastic_scattering_reaction', 'i8'),
    ('reactions', reaction, (0,)),
    ('N_reaction', 'i8'),
    ('sources', source, (1,)),
    ('N_source', 'i8'),
    ('cells', cell, (1,)),
    ('N_cell', 'i8'),
    ('lattices', lattice, (0,)),
    ('N_lattice', 'i8'),
    ('surfaces', surface, (2,)),
    ('N_surface', 'i8'),
    ('universes', universe, (1,)),
    ('N_universe', 'i8'),
    ('meshes', mesh, (1,)),
    ('N_mesh', 'i8'),
    ('structured_meshes', structured_mesh, (1,)),
    ('N_structured_mesh', 'i8'),
    ('uniform_meshes', uniform_mesh, (0,)),
    ('N_uniform_mesh', 'i8'),
    ('cell_tallies', cell_tally, (0,)),
    ('N_cell_tally', 'i8'),
    ('surface_tallies', surface_tally, (0,)),
    ('N_surface_tally', 'i8'),
    ('tallies', tally, (1,)),
    ('N_tally', 'i8'),
    ('global_tallies', global_tally, (0,)),
    ('N_global_tally', 'i8'),
    ('mesh_tallies', mesh_tally, (1,)),
    ('N_mesh_tally', 'i8'),
    ('settings', settings),
    ('implicit_capture', implicit_capture),
    ('weighted_emission', weighted_emission),
    ('weight_roulette', weight_roulette),
    ('population_control', population_control),
    ('gpu_meta', gpu_meta),
    ('bank_future', bank_future),
    ('bank_source', bank_source),
    ('bank_census', bank_census),
    ('bank_active', bank_active),
    ('idx_work', 'i8'),
    ('idx_cycle', 'i8'),
    ('idx_census', 'i8'),
    ('idx_batch', 'i8'),
    ('dd_idx', 'i8'),
    ('dd_N_local_source', 'i8'),
    ('dd_local_rank', 'i8'),
    ('k_eff', 'f8'),
    ('k_cycle_offset', 'i8'),
    ('k_cycle_length', 'i8'),
    ('k_avg', 'f8'),
    ('k_sdv', 'f8'),
    ('n_avg', 'f8'),
    ('n_sdv', 'f8'),
    ('n_max', 'f8'),
    ('C_avg', 'f8'),
    ('C_sdv', 'f8'),
    ('C_max', 'f8'),
    ('k_avg_running', 'f8'),
    ('k_sdv_running', 'f8'),
    ('gyration_radius_offset', 'i8'),
    ('gyration_radius_length', 'i8'),
    ('cycle_active', '?'),
    ('eigenvalue_tally_nuSigmaF', 'f8', (1,)),
    ('eigenvalue_tally_n', 'f8', (1,)),
    ('eigenvalue_tally_C', 'f8', (1,)),
    ('mpi_size', 'i8'),
    ('mpi_rank', 'i8'),
    ('mpi_master', '?'),
    ('mpi_work_start', 'i8'),
    ('mpi_work_size', 'i8'),
    ('mpi_work_size_total', 'i8'),
    ('mpi_work_iter', 'i8', (1,)),
    ('runtime_total', 'f8'),
    ('runtime_preparation', 'f8'),
    ('runtime_simulation', 'f8'),
    ('runtime_output', 'f8'),
    ('runtime_bank_management', 'f8'),
])

