# The following is automatically generated by code_factory.py

from numba import njit


@njit
def spectrum_probability_grid(index, neutron_inelastic_scattering_reaction, data, value):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    data[offset + index] = value


@njit
def spectrum_probability_grid_all(neutron_inelastic_scattering_reaction, data, value):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    data[start:end] = value


@njit
def spectrum_probability_grid_last(neutron_inelastic_scattering_reaction, data, value):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def spectrum_probability_grid_chunk(start, length, neutron_inelastic_scattering_reaction, data, value):
    start += neutron_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def spectrum_probability(index, neutron_inelastic_scattering_reaction, data, value):
    offset = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    data[offset + index] = value


@njit
def spectrum_probability_all(neutron_inelastic_scattering_reaction, data, value):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_length"]
    end = start + size
    data[start:end] = value


@njit
def spectrum_probability_last(neutron_inelastic_scattering_reaction, data, value):
    start = neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    size = neutron_inelastic_scattering_reaction["spectrum_probability_length"]
    end = start + size
    data[end - 1] = value


@njit
def spectrum_probability_chunk(start, length, neutron_inelastic_scattering_reaction, data, value):
    start += neutron_inelastic_scattering_reaction["spectrum_probability_offset"]
    end = start + length
    data[start:end] = value


@njit
def energy_spectrum_IDs(index, neutron_inelastic_scattering_reaction, data, value):
    offset = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    data[offset + index] = value


@njit
def energy_spectrum_IDs_all(neutron_inelastic_scattering_reaction, data, value):
    start = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = neutron_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    data[start:end] = value


@njit
def energy_spectrum_IDs_last(neutron_inelastic_scattering_reaction, data, value):
    start = neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = neutron_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    data[end - 1] = value


@njit
def energy_spectrum_IDs_chunk(start, length, neutron_inelastic_scattering_reaction, data, value):
    start += neutron_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    end = start + length
    data[start:end] = value
