# The following is automatically generated by code_factory.py

from numba import njit


@njit
def value(index, pdf_distribution, data, value):
    offset = pdf_distribution["value_offset"]
    data[offset + index] = value


@njit
def value_all(pdf_distribution, data, value):
    start = pdf_distribution["value_offset"]
    size = pdf_distribution["value_length"]
    end = start + size
    data[start:end] = value


@njit
def value_last(pdf_distribution, data, value):
    start = pdf_distribution["value_offset"]
    size = pdf_distribution["value_length"]
    end = start + size
    data[end - 1] = value


@njit
def value_chunk(start, length, pdf_distribution, data, value):
    start += pdf_distribution["value_offset"]
    end = start + length
    data[start:end] = value


@njit
def pdf(index, pdf_distribution, data, value):
    offset = pdf_distribution["pdf_offset"]
    data[offset + index] = value


@njit
def pdf_all(pdf_distribution, data, value):
    start = pdf_distribution["pdf_offset"]
    size = pdf_distribution["pdf_length"]
    end = start + size
    data[start:end] = value


@njit
def pdf_last(pdf_distribution, data, value):
    start = pdf_distribution["pdf_offset"]
    size = pdf_distribution["pdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def pdf_chunk(start, length, pdf_distribution, data, value):
    start += pdf_distribution["pdf_offset"]
    end = start + length
    data[start:end] = value


@njit
def cdf(index, pdf_distribution, data, value):
    offset = pdf_distribution["cdf_offset"]
    data[offset + index] = value


@njit
def cdf_all(pdf_distribution, data, value):
    start = pdf_distribution["cdf_offset"]
    size = pdf_distribution["cdf_length"]
    end = start + size
    data[start:end] = value


@njit
def cdf_last(pdf_distribution, data, value):
    start = pdf_distribution["cdf_offset"]
    size = pdf_distribution["cdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def cdf_chunk(start, length, pdf_distribution, data, value):
    start += pdf_distribution["cdf_offset"]
    end = start + length
    data[start:end] = value
